package com.timuwork.dao;

import com.timuwork.dataobject.AdminDO;
import com.timuwork.service.model.AdminModel;

public interface AdminDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int insert(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int insertSelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    AdminDO selectByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int updateByPrimaryKeySelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int updateByPrimaryKey(AdminDO record);

    AdminDO selectAdminByName(String adminname);
}