package com.timuwork.dao;

import com.timuwork.dataobject.OrderDO;
import com.timuwork.dataobject.OrderWithNameDO;
import com.timuwork.dataobject.OrderWithStuStatusDO;

import java.util.List;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    OrderDO selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int updateByPrimaryKey(OrderDO record);

    int insertNewOrder(OrderDO orderDO);

    OrderDO selectBySIdAndDate(OrderDO orderDO);
    List<OrderDO> selectByStuId(int sid);
    List<OrderWithNameDO> selectByDate(OrderDO orderDO);
    List<OrderWithStuStatusDO> selectStudentStatusByDate(OrderDO orderDO);
    List<OrderWithNameDO> selectAllStudentAll();
}