package com.timuwork.dao;

import com.timuwork.dataobject.StudentDO;
import com.timuwork.service.model.StudentModel;

public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    StudentDO selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    int updateByPrimaryKey(StudentDO record);

    StudentDO selectBySNameAndRoom(StudentDO studentDO);

    int updatePasswordById(StudentDO studentDO);

    StudentDO selectBySIdAndPass(StudentDO studentDO);
}