package com.timuwork.dataobject;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAdmin.adminID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAdmin.adminName
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAdmin.adminPassword
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String adminpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public AdminDO(Integer adminid, String adminname, String adminpassword) {
        this.adminid = adminid;
        this.adminname = adminname;
        this.adminpassword = adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAdmin
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public AdminDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAdmin.adminID
     *
     * @return the value of TAdmin.adminID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAdmin.adminID
     *
     * @param adminid the value for TAdmin.adminID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAdmin.adminName
     *
     * @return the value of TAdmin.adminName
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAdmin.adminName
     *
     * @param adminname the value for TAdmin.adminName
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAdmin.adminPassword
     *
     * @return the value of TAdmin.adminPassword
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAdmin.adminPassword
     *
     * @param adminpassword the value for TAdmin.adminPassword
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }
}