package com.timuwork.dataobject;

import java.util.Date;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.studentID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderTime
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderDate
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderBreakfast
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderbreakfast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderLB
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderLC
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderlc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderLCOLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderlcola;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderLSP
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderlsp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderLRICE
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderlrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderSA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer ordersa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderSB
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer ordersb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderSC
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer ordersc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderSCOLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderscola;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderSSP
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer orderssp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOrder.orderSRICE
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer ordersrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public OrderDO(Integer orderid, Integer studentid, Date ordertime, Date orderdate, Integer orderbreakfast, Integer orderla, Integer orderlb, Integer orderlc, Integer orderlcola, Integer orderlsp, Integer orderlrice, Integer ordersa, Integer ordersb, Integer ordersc, Integer orderscola, Integer orderssp, Integer ordersrice) {
        this.orderid = orderid;
        this.studentid = studentid;
        this.ordertime = ordertime;
        this.orderdate = orderdate;
        this.orderbreakfast = orderbreakfast;
        this.orderla = orderla;
        this.orderlb = orderlb;
        this.orderlc = orderlc;
        this.orderlcola = orderlcola;
        this.orderlsp = orderlsp;
        this.orderlrice = orderlrice;
        this.ordersa = ordersa;
        this.ordersb = ordersb;
        this.ordersc = ordersc;
        this.orderscola = orderscola;
        this.orderssp = orderssp;
        this.ordersrice = ordersrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOrder
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public OrderDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderID
     *
     * @return the value of TOrder.orderID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderID
     *
     * @param orderid the value for TOrder.orderID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.studentID
     *
     * @return the value of TOrder.studentID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.studentID
     *
     * @param studentid the value for TOrder.studentID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderTime
     *
     * @return the value of TOrder.orderTime
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderTime
     *
     * @param ordertime the value for TOrder.orderTime
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderDate
     *
     * @return the value of TOrder.orderDate
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderDate
     *
     * @param orderdate the value for TOrder.orderDate
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderBreakfast
     *
     * @return the value of TOrder.orderBreakfast
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderbreakfast() {
        return orderbreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderBreakfast
     *
     * @param orderbreakfast the value for TOrder.orderBreakfast
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderbreakfast(Integer orderbreakfast) {
        this.orderbreakfast = orderbreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderLA
     *
     * @return the value of TOrder.orderLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderla() {
        return orderla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderLA
     *
     * @param orderla the value for TOrder.orderLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderla(Integer orderla) {
        this.orderla = orderla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderLB
     *
     * @return the value of TOrder.orderLB
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderlb() {
        return orderlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderLB
     *
     * @param orderlb the value for TOrder.orderLB
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderlb(Integer orderlb) {
        this.orderlb = orderlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderLC
     *
     * @return the value of TOrder.orderLC
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderlc() {
        return orderlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderLC
     *
     * @param orderlc the value for TOrder.orderLC
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderlc(Integer orderlc) {
        this.orderlc = orderlc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderLCOLA
     *
     * @return the value of TOrder.orderLCOLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderlcola() {
        return orderlcola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderLCOLA
     *
     * @param orderlcola the value for TOrder.orderLCOLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderlcola(Integer orderlcola) {
        this.orderlcola = orderlcola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderLSP
     *
     * @return the value of TOrder.orderLSP
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderlsp() {
        return orderlsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderLSP
     *
     * @param orderlsp the value for TOrder.orderLSP
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderlsp(Integer orderlsp) {
        this.orderlsp = orderlsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderLRICE
     *
     * @return the value of TOrder.orderLRICE
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderlrice() {
        return orderlrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderLRICE
     *
     * @param orderlrice the value for TOrder.orderLRICE
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderlrice(Integer orderlrice) {
        this.orderlrice = orderlrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderSA
     *
     * @return the value of TOrder.orderSA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrdersa() {
        return ordersa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderSA
     *
     * @param ordersa the value for TOrder.orderSA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrdersa(Integer ordersa) {
        this.ordersa = ordersa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderSB
     *
     * @return the value of TOrder.orderSB
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrdersb() {
        return ordersb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderSB
     *
     * @param ordersb the value for TOrder.orderSB
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrdersb(Integer ordersb) {
        this.ordersb = ordersb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderSC
     *
     * @return the value of TOrder.orderSC
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrdersc() {
        return ordersc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderSC
     *
     * @param ordersc the value for TOrder.orderSC
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrdersc(Integer ordersc) {
        this.ordersc = ordersc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderSCOLA
     *
     * @return the value of TOrder.orderSCOLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderscola() {
        return orderscola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderSCOLA
     *
     * @param orderscola the value for TOrder.orderSCOLA
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderscola(Integer orderscola) {
        this.orderscola = orderscola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderSSP
     *
     * @return the value of TOrder.orderSSP
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrderssp() {
        return orderssp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderSSP
     *
     * @param orderssp the value for TOrder.orderSSP
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrderssp(Integer orderssp) {
        this.orderssp = orderssp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOrder.orderSRICE
     *
     * @return the value of TOrder.orderSRICE
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getOrdersrice() {
        return ordersrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOrder.orderSRICE
     *
     * @param ordersrice the value for TOrder.orderSRICE
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setOrdersrice(Integer ordersrice) {
        this.ordersrice = ordersrice;
    }
}