package com.timuwork.dataobject;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TStudent.student_ID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TStudent.student_Name
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TStudent.student_Room
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String studentRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TStudent.room_Position
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String roomPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TStudent.student_College
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String studentCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TStudent.student_Password
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    private String studentPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public StudentDO(Integer studentId, String studentName, String studentRoom, String roomPosition, String studentCollege, String studentPassword) {
        this.studentId = studentId;
        this.studentName = studentName;
        this.studentRoom = studentRoom;
        this.roomPosition = roomPosition;
        this.studentCollege = studentCollege;
        this.studentPassword = studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TStudent
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public StudentDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TStudent.student_ID
     *
     * @return the value of TStudent.student_ID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TStudent.student_ID
     *
     * @param studentId the value for TStudent.student_ID
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TStudent.student_Name
     *
     * @return the value of TStudent.student_Name
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TStudent.student_Name
     *
     * @param studentName the value for TStudent.student_Name
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TStudent.student_Room
     *
     * @return the value of TStudent.student_Room
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getStudentRoom() {
        return studentRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TStudent.student_Room
     *
     * @param studentRoom the value for TStudent.student_Room
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setStudentRoom(String studentRoom) {
        this.studentRoom = studentRoom == null ? null : studentRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TStudent.room_Position
     *
     * @return the value of TStudent.room_Position
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getRoomPosition() {
        return roomPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TStudent.room_Position
     *
     * @param roomPosition the value for TStudent.room_Position
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setRoomPosition(String roomPosition) {
        this.roomPosition = roomPosition == null ? null : roomPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TStudent.student_College
     *
     * @return the value of TStudent.student_College
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getStudentCollege() {
        return studentCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TStudent.student_College
     *
     * @param studentCollege the value for TStudent.student_College
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setStudentCollege(String studentCollege) {
        this.studentCollege = studentCollege == null ? null : studentCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TStudent.student_Password
     *
     * @return the value of TStudent.student_Password
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TStudent.student_Password
     *
     * @param studentPassword the value for TStudent.student_Password
     *
     * @mbg.generated Thu Feb 13 15:41:30 CST 2020
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }
}